version: '2.4'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=taxonomy
      - MYSQL_ROOT_PASSWORD=baixing123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
  app:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  db-data:
