version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=taxonomy
      - MYSQL_USER=root
      - MYSQL_PASSWORD=baixing123
      - MYSQL_ROOT_PASSWORD=baixing123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
